import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { getLocale } from "next-intl/server";
import { ThemeProvider } from "@/common/providers/theme-provider";
import { SITE_CONFIG } from "@/config";
import Script from "next/script";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/common/components/nav/Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <ClerkProvider>
      <html lang={locale} suppressHydrationWarning>
        <body className={`${montserrat.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            forcedTheme="light"
            disableTransitionOnChange
          >
            <Navbar />
            <main>{children}</main>
          </ThemeProvider>
          {SITE_CONFIG.isProd && (
            <Script
              id="CookieConsent"
              src="https://policy.app.cookieinformation.com/uc.js"
              data-culture="EN"
              data-gcm-version="2.0"
              type="text/javascript"
            />
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
